### ISSUE TITLE
clone代码之后gradle失败

### ISSUE THREAD

**Issue by wsclwps123** [doggycoder/AudioVideo#1]
Gradle 'media_recorder_api_18' project refresh failed
Error:Cause: unable to find valid certification path to requested target

**Comment by doggycoder** [comment]
将gradle版本改为你的电脑上有的gradle版本试试，我不太确定是不是这个问题

**Comment by doggycoder** [comment]
@wsclwps123 将gradle版本改为你的电脑上有的gradle版本试试，我不太确定是不是这个问题
