### ISSUE TITLE
解码h264一帧怎么保存为jpg?

### ISSUE THREAD

**Issue by leestars** [doggycoder/AudioVideo#2]

**Comment by doggycoder** [comment]
@leestars 
1. 解码h264得到yuv
2. yuv转换得到rgba
3. 保存rgba为jpg

**Comment by leestars** [comment]
@doggycoder 大神能不能给示例代码

**Comment by doggycoder** [comment]
@leestars 解码yuv 在这个里面有，也有rgba转yuv的代码，反推一下就是yuv转rgba了，拿到rgba再保存jpg，Android也提供了方法。

**Comment by leestars** [comment]
@doggycoder 我在这方面了解甚少,我看了你的代码也不是很懂，我没看明白哪里是解码后的yuv数据？

**Comment by doggycoder** [comment]
@leestars http://blog.csdn.net/junzia/article/details/68952183
